import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/componet/Header";
import MainHeader from "@/componet/MainHeader";
import Navbar from "@/componet/Navbar";
import MobileNav from "@/componet/MobileNav";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
const inter = Inter({ subsets: ["latin"] });
import Footer from "@/componet/Footer";
import Testimonial from "@/componet/Testimonial";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <MainHeader/>
        <Navbar/>
        <MobileNav/>
        {children}
       
        <Testimonial/>
        <Footer/>
        </body>
    </html>
  );
}
